blogapplication/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.PostListView.as_view(), name='posts_list'),
    path('posts/<pk>', views.post_detail, name='posts_detail'),
    path('posts/<post_id>/comment', views.post_comment,
         name='posts_comment'),
    path('ticket', views.ticket, name='ticket'),
]

blogapplication/blogapplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blogapplication/blog/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django_jalali.db import models as jmodels
from django.urls import reverse



# Create your models here.

class PublishedManager(models.Manager):
    def queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"
        REJECTED = "RJ", "Rejected"

    # relations
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts', verbose_name='نویسنده')
    # data fields
    title = models.CharField(max_length=200, verbose_name='عنوان')
    description = models.TextField()
    slug = models.SlugField(max_length=200, verbose_name='اسلاگ')
    # date
    publish = jmodels.jDateTimeField(default=timezone.now, verbose_name='تاریخ انتشار')
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    # choice fields
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT, verbose_name='وضعیت')
    # manager
    # objects = models.Manager()
    objects = jmodels.jManager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:posts_detail', args=[self.id])


class Ticket(models.Model):
    message = models.TextField(verbose_name='پیام')
    name = models.CharField(max_length=150, verbose_name='نام')
    phone = models.CharField(max_length=11, verbose_name='شماره تلفن')
    email = models.EmailField(verbose_name='ایمیل')
    subject = models.CharField(max_length=250, verbose_name='موضوع')

    class Meta:
        verbose_name = 'تیکت'
        verbose_name_plural = 'تیکت ها'

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                               related_name='comments', verbose_name='پست')
    body = models.TextField(verbose_name='متن کامنت')
    name = models.CharField(max_length=150, verbose_name='نام')
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')
    active = models.BooleanField(default=False, verbose_name='وضعیت')

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

    def __str__(self):
        return f"{self.name}:{self.post}"

blogapplication/blog/forms.py
from django import forms
from .models import Comment


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش مشکل', 'گزارش مشکل'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=150, required=True)
    phone = forms.CharField(min_length=11, max_length=11, required=True)
    email = forms.EmailField()
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not phone.isdigit():
            raise forms.ValidationError('شماره تلفن باید عددی باشد!')
        else:
            return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 3:
            raise forms.ValidationError('نام کوتاه میباشد!')
        else:
            return phone

    class Meta:
        model = Comment
        fields = ('name', 'body')

blogapplication/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST


# Create your views here.

def index(request):
    return render(request, 'blog/index.html')


# def post_list(request):
#     posts = Post.published.all()
#     paginator = Paginator(posts, 3)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginator.get_page(page_number)
#     except EmptyPage:
#         posts = paginator.get_page(paginator.num_pages)
#     except PageNotAnInteger:
#         posts = paginator.get_page(1)
#     context = {'posts': posts}
#     return render(request, 'blog/list.html', context)


# ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
# | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/list.html'


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {'post': post,
               'form': form,
               'comments': comments
               }
    return render(request, 'blog/detail.html', context)


# ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
# | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        print(require_POST)
        print(request)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'],
                                  phone=cd['phone'], email=cd['email'],
                                  subject=cd['subject'])
            return redirect("blog:ticket")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {"form": form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, "forms/comment.html", context)

blogapplication/blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}
{% block title %}post datail{% endblock %}

{% block content %}
    <h1>post detail</h1>
    <h2>{{ post.title }} (by {{ post.author }})</h2>
    <p>{{ post.description | markdown }}</p>
    <hr>
    <p>{{ post.publish | jformat:'%Y/%m/%d - %H:%M' }}</p>
    <div>
        {% with comments.count as cm_count %}
            {{ cm_count }} comment {{ cm_count | pluralize }}
            </div>

            <div>
                {% for cm in comments %}
                    {{ cm.body | linebreaks }}
                    {{ cm.name }}
                    <hr>
                {% empty %}
                    کامنتی وجود ندارد
                {% endfor %}
            </div>
        {% endwith %}
    <form method="post" action="{% url 'blog:posts_comment' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="افزودن کامنت">
    </form>

{% endblock %}

blogapplication/blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}post list{% endblock %}
{% block content %}
   <h2>آمار</h2>
    <p>تعداد پست ها: {% total_posts %}</p>
    <p>تعداد کامنت ها: {% total_comments %}</p>
    <p>{% last_post_date %}تاریخ آخرین پست: </p>

    {% latest_posts 5 %}

    <h2>محبوب ترین پست ها</h2>
    {% most_popular_posts as pop_posts %}
    {% for post in pop_posts %}
        <br>
         <a href="{{ post.get_absolute_url }}">{{ post.title }}: with {{ post.comments_count }} comments</a>
    {% endfor %}
{% endblock %}

blogapplication/blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% block content %}
    <h1>post list</h1>
    <ol style="--length: {{ posts|length }}" role="list">
        {% for post in posts %}
            <li style="--i: {{ forloop.counter }}">
                <h3>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h3>
                <p>{{ post.description | truncatewords:4 }}</p>
            </li>
        {% endfor %}
    </ol>
    {% include 'partials/pagination.html' with page=page_obj %}
{% endblock %}

blogapplication/blog/templates/forms/comment.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% block title %}post comment{% endblock %}

{% block content %}
    {% if comment %}
        کامنت شما ثبت شد.
        <a href="{{ post.get_absolute_url }}">بازگشت به پست</a>
    {% else %}
        <form method="post" action="{% url 'blog:posts_comment' post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="افزودن کامنت">
        </form>
    {% endif %}

{% endblock %}

blogapplication/blog/templates/forms/ticket.html
{% extends 'parent/base.html' %}
{% block title %}ticket{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        نام و نام خانوادگی:
        <input type="text" name="name" required {% if form.name.value %}value="{{ form.name.value }}"{% endif %}>
        <br>
        <br>
        ایمیل:
        <input type="email" name="email" {% if form.email.value %}value="{{ form.email.value }}"{% endif %}>
        <br>
        <br>
        شماره تماس:
        <input type="text" name="phone" required maxlength="11"
               {% if form.phone.value %}value="{{ form.phone.value }}"{% endif %}>
        <br>
        <br>
        متن:
        <textarea name="message">{% if form.message.value %}{{ form.message.value }}{% endif %}</textarea>
        <br>
        <br>
        <select name="subject">
            <option value="پیشنهاد" {% if form.subject.value == "پیشنهاد" %} selected  {% endif %}> پیشنهادات</option>
            <option value="انتقاد" {% if form.subject.value == "انتقاد" %} selected  {% endif %}> انتقادات</option>
            <option value="گزارش" {% if form.subject.value == "گزارش" %} selected  {% endif %}> گزارش</option>
        </select>
        <br>
        <input type="submit" value="ثبت تیکت">
    </form>
    {% if form.errors %}
        لطفا خطاهای زیر را اصلاح کنید!
        <br>
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
{% endblock %}

blogapplication/blog/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
{#{% include 'partials/header.html' %}#}
{#{% include 'partials/navigation.html' %}#}
{% block content %}{% endblock %}
{#{% include 'partials/footer.html' %}#}
</body>
</html>

blogapplication/blog/templates/partials/footer.html
<p>footer</p>

blogapplication/blog/templates/partials/header.html
<p>header</p>

blogapplication/blog/templates/partials/latest_posts.html
{% load jformat %}
<div>
    <h2>آخرین پست ها</h2>
    {% for post in l_posts %}
    <p><a href="{{ post.get_absolute_url }}">{{ post.title }}: {{ post.publish | jformat:'%Y/%m/%d - %H:%M' }}</a></p>
    {% endfor %}
</div>

blogapplication/blog/templates/partials/navigation.html
<p>navigation</p>

blogapplication/blog/templates/partials/pagination.html
<nav class="my-5" aria-label="navigation">
    <ul class="pagination d-inline-block d-md-flex justify-content-center">

{% if page.has_previous %}
    <li class="page-item">
    	<a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1" aria-disabled="true">قبل</a>
    </li>

  {% if page.number > 3 %}
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% if page.number > 4 %}
      <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
    {% endif %}
  {% endif %}

{% endif %}

{% for num in page.paginator.page_range %}
  {% if page.number == num %}
    <li class="page-item"><a class="page-link active" href="?page={{ num }}">{{ num }}</a></li>
  {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
  {% endif %}
{% endfor %}

{% if page.has_next %}
  {% if page.number < page.paginator.num_pages|add:'-3' %}
    <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
  {% elif page.number < page.paginator.num_pages|add:'-2' %}
      <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>

  {% endif %}
    <li class="page-item">
    	<a class="page-link" href="?page={{ page.next_page_number }}">بعد</a>
    </li>
{% endif %}

	</ul>
</nav>